esphome:
  name: m5stack-core-s3
  friendly_name: M5Stack CoreS3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://RAR/esphome-axp2101
    components: [ axp2101, aw9523 ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXX"

ota:
  password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XXX"
    password: "XXX"

captive_portal:

web_server:
  port: 80

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO37
  miso_pin: GPIO35

i2c:
  - id: bus_a
    sda: GPIO12
    scl: GPIO11
    scan: True

aw9523:
  id: aw9523_component
  address: 0x58

axp2101:
  id: axp2101_component
  model: M5CORES3

sensor:
  - platform: axp2101
    axp2101_id: axp2101_component
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery Level"
    temperature:
      name: "PMU Temperature"

number:
  - platform: axp2101
    axp2101_id: axp2101_component
    backlight:
      name: "Backlight Brightness"
    charging_led_mode:
      name: "Charging LED Mode"
      # Modes: 0=Off, 1=Blink 1Hz, 2=Blink 4Hz, 3=On, 4=Auto (controlled by charger)

touchscreen:
  - platform: ft63x6
    i2c_id: bus_a
    on_touch:
      - logger.log:
          format: Touch %d at (%d, %d)
          args: [touch.id, touch.x, touch.y]

binary_sensor:
  # AXP2101 binary sensors
  - platform: axp2101
    axp2101_id: axp2101_component
    battery_charging:
      name: "Battery Charging"
    vbus_connected:
      name: "USB Connected"
    low_battery_level1:
      name: "Low Battery Warning"
      # Triggers when battery level drops below ~15%
      on_press:
        - logger.log: "Low battery warning (level 1)!"
    low_battery_level2:
      name: "Critical Battery Warning"
      # Triggers when battery level drops below ~5%
      on_press:
        - logger.log: "Critical battery warning (level 2)!"
    pkey_short_press:
      name: "Power Button Short Press"
      on_press:
        - logger.log: "Power button short press!"
    pkey_long_press:
      name: "Power Button Long Press"
      on_press:
        - logger.log: "Power button long press!"
    # Optional: Track button state with positive/negative edges
    # pkey_positive:
    #   name: "Power Button Pressed"
    # pkey_negative:
    #   name: "Power Button Released"

  # Touchscreen buttons
  - platform: touchscreen
    name: Left Touch Button
    x_min: 0
    x_max: 106
    y_min: 120
    y_max: 140

  - platform: touchscreen
    name: Middle Touch Button
    x_min: 107
    x_max: 213
    y_min: 120
    y_max: 140

  - platform: touchscreen
    name: Right Touch Button
    x_min: 214
    x_max: 320
    y_min: 120
    y_max: 140

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 24

display:
  - platform: ili9xxx
    model: M5STACK
    id: my_display
    dimensions: 320x240
    cs_pin: GPIO3
    dc_pin:
      number: GPIO35
      allow_other_uses: true
    reset_pin:
      aw9523: aw9523_component
      port: 1
      pin: 1
      mode:
        output: true
    data_rate: 8000000
    invert_colors: true
    update_interval: 100ms
    lambda: |-
      it.print(0, 0, id(roboto), "Hello World!");
      
